### ISSUE TITLE
New digest breaks on MacOs

### ISSUE THREAD

**Issue by vdel** [Deepomatic/dmake#236]
The digest function is still broken for two reasons:

1) #230 introduced a new hashing method that do not work on MacOS.

The reason is due to the output of the md5 function:

On Mac, `find . -type f -print0 | xargs -0 md5 -r` outputs this:
`MD5 (./MANIFEST.in) = 0f57c392c6c168939833a3e893068e37`

On Linux: `find . -type f -print0 | xargs -0 md5sum` outputs this:
`0f57c392c6c168939833a3e893068e37  ./MANIFEST.in`

The solution is to use `md5 -r` on MacOs but it only separates the hash and the path with one space (instead of two for Linux) so we must account for that too

2) For submodules, the `.git` file can point to the parent git repo with an absolute path that may differ from one computer to another. I propose to ignore the `.git` files for now.

**Comment by thomas-riccardi** [comment]
1. The issue is double space vs one space between md5sum columns. Swapping swapping sort and cut removes the paths from the list: we don't want that

2. Those repositories are less portable: moving the whole root directory will break the gitlinks, I have no idea how they were built. I'm not sure we want to support them. Do you reproduce the issue with a fresh clone? Which git version do you use? Did you use a special git frontend?
